### PR TITLE
feat: add cluster qa

### PR DESCRIPTION
**Pull request by osbornjd**
Adds cluster QA modules to job 0. Need to modify the production scripts to move the output `HIST_*` files to wherever the calo files go on gpfs so that they can be included in the hadd command

### CODE REVIEW

**Comment by klendathu2k** [comment]
> Adds cluster QA modules to job 0. Need to modify the production scripts to move the output `HIST_*` files to wherever the calo files go on gpfs so that they can be included in the hadd command

Calorimeter histograms are being staged out to `/sphenix/data/data02/sphnxpro/calohist/run_*`.  Do you need them in the same directory, or does it make sense to place them under their own directory structure?  (e.g. `trkrhist/run_*`)

**Comment by osbornjd** [comment]
@pinkenburg if we put them in the same directory, will the existing machinery just hadd everything together and make it all available to QAhtml? If so it is probably just easier to put them in the same place

**Comment by pinkenburg** [comment]
I think this is a question for Nathan, he took over the machinery. It might be easier to keep this separate at this stage since they come from separate jobs but I would defer to him

**Comment by klendathu2k** [comment]
I'm going to pull this in and put it into production.  I'll send outputs to `/sphenix/data/data02/sphnxpro/clusterhist/`

**Comment by ngrau** [comment]
It is fine with me if the tracking QA files are in the same directory as the calo. All I will need to know if there is just one set of files to hadd or if the calo and tracking are in different files.  Either works and can easily be added to the scripts.

**Comment by osbornjd** [comment]
All the files will have the prefix `HIST_*` so the hadd should just be able to put them all together by the same command. But the files that hold the calo histograms and the tracking histograms will technically be different files

**Pull request merged**
